// @peakprep/mathmog/core/learn/modules — Fractions ↔ Decimals ↔ Percents
// Learn modules (Phase 2A.2, final topic slice).
//
// V1 DIRECTION RESTRICTION (design doc §6.5, decision deferred to this
// slice): items are fraction → decimal only. An "item" in the full model is
// a (fraction, direction) pair; v1 ships one direction because (a) the
// retrieval fact is the equivalence itself — one direction per fact is
// enough for acquisition, and Drill exercises all four directions for
// retention; (b) percent answers are the decimal ×100 (near-duplicate
// retrieval), and the →fraction directions have string answers ("2/3"),
// which would widen the aggregate's `TAnswer = number` for marginal gain;
// (c) 27 items, not 100+. Item ids are direction-implicit ("2/3"); a
// widened v2 mints new ids for new directions — per-item state is
// session-only, so there is no migration cost. Caution for v2 (reviewer
// ruling): decimal→fraction has a different error taxonomy (0.375 → 3/8 vs
// 3/7 vs 37/100), so its pools are a full new curation surface, not a
// mirror.
//
// Enumeration mirrors the Drill generator: numerators come straight from
// `fractionBasesByDenominator` (so the two modes can't drift), denominators
// ascending then numerators ascending — the reference-card order.
// Denominator 2 was added to the Drill data in this slice (reviewer ruling:
// the registry labels promised 1/2 and the fact set didn't deliver it — a
// trust bug for a confidence-rebuilding audience; the fix is Drill-side,
// never a Learn-only item, to keep "same data, two modes" intact).
//
// Prompt carries the direction ("2/3 as a decimal"): direction is CONTENT,
// not presentation — the Drill parallel is "Convert 2/3 to a decimal",
// generated by the topic. The "= ?" suffix stays render-time (2A.4).
//
// The canonical answer is the TRUNCATED repeating form at the Drill's
// prompt precision (2/3 → 0.66, 5/9 → 0.55, 1/7 → 0.142), not the rounded
// form (reviewer ruling): the truncated form IS the pattern — ninths as
// 0.nn, and all six sevenths as literal substrings of the 142857 wheel
// (rounding breaks three of them) — and it is the reference card's primary
// value, so Reference ↔ Learn show the same number. The schoolroom
// "0.555… rounds to 0.56" convention is a presentation concern: 2A.4 may
// render a trailing ellipsis on See cards for items with a multi-member
// accepted family. The Recall grader accepts the whole Drill family either
// way (`FRACTION_ACCEPTED_DECIMALS`), and a test pins each canonical inside
// its family.
//
// Distractor curation (Q6: hand-picked pools, ≥1 plausible near-miss;
// `assembleRecognizeOptions` samples 3, so 4–5-entry pools buy layout
// variety). Fraction-context confusion sources, rough priority order:
// - digits-as-decimal slips — reading the fraction's digits as the decimal
//   (3/8 → 0.38, 1/4 → 0.14), and the denominator/numerator-as-decimal
//   variants (1/5 → 0.5, 1/4 → 0.4, 3/5 → 0.3);
// - complements — n/d confused with (d−n)/d (1/3 ↔ 2/3, 3/8 ↔ 5/8); for
//   sevenths this is also the which-rotation-of-142857 slip;
// - within-set confusions — another fraction's actual decimal (2/3 vs 3/4
//   vs 4/5; 0.857 vs 0.875; 0.833 vs 0.857), the design doc §1.1 source;
// - digit transpositions where they look credible (0.143/0.134,
//   0.625/0.652);
// - percent-magnitude slips (1/5 → 0.05, 1/9 → 0.09).
// Prefer DUAL-IDENTITY entries — simultaneously a procedural slip and
// another fact's actual value (0.56 for 5/6 = digits slip + 5/9; 0.286 for
// 5/7 = rotation + complement): whichever error the student makes, the
// feedback is diagnostic.
//
// Structural-signature rules (the parity-rule generalization from the
// squares/cubes passes — "any structural signature of the answer family"):
// - ACCEPTED-FAMILY EXCLUSION: no distractor may appear in the item's full
//   accepted family — 0.67 can never distract 2/3. The leak isn't a
//   giveaway but a false negative: marking a Drill-correct answer wrong.
// - ROUNDING-NEIGHBOR EXCLUSION (sharper, this topic's reviewer pass): also
//   exclude any value that is a correct rounding/truncation of the true
//   value at a precision the family covers (0.9 for 8/9, 0.8 for 5/6) —
//   it punishes the better student. Values below the family's precision
//   floor (0.4 for 3/7) are allowed only with an independent error
//   identity.
// - Extremal-position rule: the canonical must not be the guaranteed max or
//   min of every option draw — magnitude extremity is a signature too.
//   Every pool keeps ≥1 distractor on each side of the answer.
// - Repeating-digit signature: doubled-digit canonicals (0.33, 0.66, 0.11,
//   0.22, 0.44, 0.55, 0.77, 0.88) take ≥1 doubled-digit distractor.
// - Eighths terminal signature: eighths end in -25/-75 at three places;
//   each eighths pool keeps ≥1 three-place distractor ending in 5.
// Inherited TODO for any future curation pass (reviewer contract note):
// signature coverage is pool-guaranteed, not draw-guaranteed — a 4-pool's
// single doubled-digit decoy misses 25% of presentations. Upgrading means a
// second signature-bearing decoy per affected pool.

import {
  acceptedDecimalFamily,
  fractionBasesByDenominator,
  truncateFraction,
} from '../../math-problems';
import type { LearnDistractorSet, LearnItem, LearnModuleDef } from '../types';
import { mathmogLearnModuleId } from '../mathmog-binding';
import { registryScopeLabel } from './scope-label';

/** Denominators with curated facts, ascending — the Drill's full set. */
const ALL_DENOMINATORS = [2, 3, 4, 5, 6, 7, 8, 9] as const;

/**
 * One curated pool per item, keyed by item id. 27 items = every
 * (numerator, denominator) pair the Drill generates — the single curation
 * surface for the topic. Hand-curated (Q6): each entry was chosen, not
 * derived; sources and signature rules in the header comment.
 */
const FRACTION_DISTRACTORS: Record<string, number[]> = {
  // halves — 0.5
  '1/2': [0.12, 0.2, 0.25, 0.75],
  // thirds — 0.33 / 0.66
  '1/3': [0.67, 0.66, 0.13, 0.25, 0.44],
  '2/3': [0.33, 0.23, 0.75, 0.56],
  // fourths — 0.25 / 0.75
  '1/4': [0.4, 0.14, 0.75, 0.2],
  '3/4': [0.25, 0.34, 0.8, 0.67],
  // fifths — 0.2 / 0.4 / 0.6 / 0.8
  '1/5': [0.5, 0.15, 0.25, 0.05],
  '2/5': [0.25, 0.5, 0.2, 0.6],
  '3/5': [0.35, 0.4, 0.3, 0.57, 0.75],
  '4/5': [0.45, 0.4, 0.2, 0.75, 0.875],
  // sixths — 0.166 / 0.833
  '1/6': [0.6, 0.125, 0.2, 0.667],
  '5/6': [0.56, 0.875, 0.6, 0.857],
  // sevenths — the 142857 rotations; complements are the rotation slips
  '1/7': [0.17, 0.125, 0.134, 0.286],
  '2/7': [0.27, 0.143, 0.268, 0.25, 0.429],
  '3/7': [0.37, 0.492, 0.571, 0.4],
  '4/7': [0.47, 0.517, 0.429, 0.6],
  '5/7': [0.57, 0.741, 0.75, 0.286],
  '6/7': [0.67, 0.875, 0.833, 0.143],
  // eighths — 0.125 / 0.375 / 0.625 / 0.875
  '1/8': [0.8, 0.18, 0.25, 0.375, 0.111],
  '3/8': [0.38, 0.625, 0.35, 0.357],
  '5/8': [0.58, 0.375, 0.652, 0.6],
  '7/8': [0.78, 0.857, 0.125, 0.8, 0.89],
  // ninths — the 0.nn repeaters
  '1/9': [0.19, 0.9, 0.125, 0.22, 0.09],
  '2/9': [0.29, 0.25, 0.11, 0.286],
  '4/9': [0.49, 0.45, 0.33, 0.429],
  '5/9': [0.59, 0.44, 0.571, 0.65],
  '7/9': [0.79, 0.875, 0.22, 0.87],
  '8/9': [0.98, 0.875, 0.11, 0.83],
};

/**
 * The truncated repeating form at the Drill's prompt precision — exact
 * integer truncation via the 2D.1 policy helpers (no float artifacts).
 */
const canonicalDecimal = (num: number, den: number): number =>
  truncateFraction(num, den, fractionBasesByDenominator[den].precision);

/**
 * Every decimal the Drill grades as correct, per item — derived straight
 * from the 2D.1 precision policy, the same function that builds the Drill's
 * `answers` maps, so Learn and Drill cannot disagree about a family. The
 * 2A.4 Recall grader accepts any member (matching the Drill's number
 * input); curation excludes all members from the item's distractor pool.
 */
export const FRACTION_ACCEPTED_DECIMALS: Record<string, number[]> =
  Object.fromEntries(
    ALL_DENOMINATORS.flatMap(den =>
      fractionBasesByDenominator[den].numerators.map(num => [
        `${num}/${den}`,
        acceptedDecimalFamily(num, den),
      ])
    )
  );

const fractionItem = (num: number, den: number): LearnItem<string, number> => ({
  id: `${num}/${den}`,
  prompt: `${num}/${den} as a decimal`,
  answer: canonicalDecimal(num, den),
});

/** Denominators ascending, numerators ascending — reference-card order. */
const itemsForDenominators = (dens: readonly number[]): LearnItem<string, number>[] =>
  dens.flatMap(den =>
    fractionBasesByDenominator[den].numerators.map(num => fractionItem(num, den))
  );

const fractionsModule = (
  scopeId: string,
  dens: readonly number[]
): LearnModuleDef<string, number> => {
  const items = itemsForDenominators(dens);
  return {
    id: mathmogLearnModuleId('fraction_conversions', scopeId),
    label: registryScopeLabel('fraction_conversions', scopeId),
    items,
    distractorSets: items.map(
      (item): LearnDistractorSet<number> => ({
        itemId: item.id,
        distractors: FRACTION_DISTRACTORS[item.id],
      })
    ),
  };
};

/**
 * One module per registry scope; denominator lists match the Drill's
 * `fractionDenominatorsForScope` (pinned by test).
 */
export const FRACTION_CONVERSIONS_LEARN_MODULES: LearnModuleDef<string, number>[] = [
  fractionsModule('fractions_full', ALL_DENOMINATORS),
  fractionsModule('fractions_friendly', [2, 4, 5]),
  fractionsModule('fractions_halves_fourths', [2, 4]),
  fractionsModule('fractions_fifths', [5]),
  fractionsModule('fractions_eighths', [8]),
  fractionsModule('fractions_thirds', [3]),
  fractionsModule('fractions_sixths', [6]),
  fractionsModule('fractions_sevenths', [7]),
  fractionsModule('fractions_ninths', [9]),
];
